# Generated by Django 4.2.1 on 2023-06-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('anoLectivo', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=10)),
                ('semestre', models.CharField(choices=[(1, '1'), (2, '2')], default=1, max_length=4)),
                ('ano', models.IntegerField(default=2021)),
                ('ects', models.IntegerField()),
                ('topicosAbordados', models.TextField(blank=True, max_length=1000)),
                ('ranking', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=2)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('funcao', models.CharField(blank=True, choices=[(1, 'Aluno'), (2, 'Professor')], default=1, max_length=10)),
                ('linkLusofona', models.URLField(blank=True)),
                ('linkLinkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ano', models.DateTimeField(auto_now_add=True)),
                ('criador', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('link', models.URLField()),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2023)),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('relatorio', models.URLField(max_length=1000)),
                ('linkGithub', models.URLField(max_length=1000)),
                ('video', models.URLField(max_length=1000)),
                ('autor', models.ManyToManyField(related_name='autorTFC', to='portfolio.pessoa')),
                ('orientadores', models.ManyToManyField(related_name='orientadores', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=2000)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('ano', models.IntegerField(default=2023)),
                ('linkGithub', models.URLField(blank=True, max_length=1000)),
                ('linkYoutube', models.URLField(blank=True, max_length=1000)),
                ('participantes', models.ManyToManyField(to='portfolio.pessoa')),
                ('tecnologias', models.ManyToManyField(to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=1000)),
                ('disciplinas', models.ManyToManyField(to='portfolio.cadeira')),
                ('projetos', models.ManyToManyField(to='portfolio.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docentes_praticas',
            field=models.ManyToManyField(related_name='docentes', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(blank=True, to='portfolio.tecnologia'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.projeto'),
        ),
    ]
